# ============================================================
#  CSV Cleaner & Report Generator
#  Author  : Silver Bullet (github.com/silverbullet-ai)
#  Version : 1.0
# ============================================================

import pandas as pd
import os
from datetime import datetime


def load_csv(filepath: str) -> pd.DataFrame:
    """Load a CSV file into a DataFrame."""
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"File not found: {filepath}")
    df = pd.read_csv(filepath)
    print(f"[✓] Loaded '{filepath}' — {df.shape[0]} rows, {df.shape[1]} columns\n")
    return df


def analyze(df: pd.DataFrame) -> dict:
    """Analyze the DataFrame and return a summary report."""
    report = {
        "total_rows": len(df),
        "total_columns": len(df.columns),
        "duplicate_rows": int(df.duplicated().sum()),
        "total_missing_cells": int(df.isnull().sum().sum()),
        "columns": {}
    }

    for col in df.columns:
        missing = int(df[col].isnull().sum())
        missing_pct = round((missing / len(df)) * 100, 1)
        unique = int(df[col].nunique(dropna=True))
        dtype = str(df[col].dtype)

        if missing_pct == 0:
            status = "Clean"
        elif missing_pct < 20:
            status = f"Low missing ({missing_pct}%)"
        else:
            status = f"High missing ({missing_pct}%)"

        report["columns"][col] = {
            "dtype": dtype,
            "missing": missing,
            "missing_pct": missing_pct,
            "unique_values": unique,
            "status": status
        }

    return report


def clean(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean the DataFrame:
    - Strip whitespace from string columns
    - Remove fully duplicate rows
    - Fill missing numeric values with column median
    - Fill missing string values with 'Unknown'
    """
    cleaned = df.copy()

    # Strip whitespace from string columns
    for col in cleaned.select_dtypes(include="object").columns:
        cleaned[col] = cleaned[col].str.strip()

    # Remove duplicate rows
    before = len(cleaned)
    cleaned = cleaned.drop_duplicates()
    removed = before - len(cleaned)
    if removed:
        print(f"[✓] Removed {removed} duplicate row(s)")

    # Fill missing values
    for col in cleaned.columns:
        if cleaned[col].dtype in ["float64", "int64"]:
            median_val = cleaned[col].median()
            cleaned[col] = cleaned[col].fillna(median_val)
        else:
            cleaned[col] = cleaned[col].fillna("Unknown")

    print("[✓] Missing values filled")
    return cleaned


def save_cleaned(df: pd.DataFrame, original_path: str) -> str:
    """Save cleaned DataFrame to a new CSV file."""
    base = os.path.splitext(original_path)[0]
    output_path = f"{base}_cleaned.csv"
    df.to_csv(output_path, index=False)
    print(f"[✓] Cleaned CSV saved → {output_path}")
    return output_path


def save_report(report: dict, original_path: str) -> str:
    """Save the analysis report as a .txt file."""
    base = os.path.splitext(original_path)[0]
    report_path = f"{base}_report.txt"

    lines = []
    lines.append("=" * 50)
    lines.append("  CSV CLEANING REPORT")
    lines.append(f"  Generated : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"  File      : {original_path}")
    lines.append("=" * 50)
    lines.append("")
    lines.append("SUMMARY")
    lines.append("-" * 30)
    lines.append(f"  Total rows          : {report['total_rows']}")
    lines.append(f"  Total columns       : {report['total_columns']}")
    lines.append(f"  Duplicate rows      : {report['duplicate_rows']}")
    lines.append(f"  Total missing cells : {report['total_missing_cells']}")
    lines.append("")
    lines.append("COLUMN DETAILS")
    lines.append("-" * 30)

    for col, info in report["columns"].items():
        lines.append(f"  {col}")
        lines.append(f"    Type          : {info['dtype']}")
        lines.append(f"    Missing       : {info['missing']} ({info['missing_pct']}%)")
        lines.append(f"    Unique values : {info['unique_values']}")
        lines.append(f"    Status        : {info['status']}")
        lines.append("")

    lines.append("=" * 50)
    lines.append("  Generated by Silver Bullet | github.com/silverbullet-ai")
    lines.append("=" * 50)

    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    print(f"[✓] Report saved → {report_path}")
    return report_path


def print_report(report: dict):
    """Print the report to the terminal."""
    print("=" * 50)
    print("  CSV CLEANING REPORT")
    print("=" * 50)
    print(f"  Rows          : {report['total_rows']}")
    print(f"  Columns       : {report['total_columns']}")
    print(f"  Duplicates    : {report['duplicate_rows']}")
    print(f"  Missing cells : {report['total_missing_cells']}")
    print()
    print(f"  {'Column':<20} {'Type':<10} {'Missing':<10} {'Unique':<10} Status")
    print("  " + "-" * 68)
    for col, info in report["columns"].items():
        print(f"  {col:<20} {info['dtype']:<10} {str(info['missing']):<10} {str(info['unique_values']):<10} {info['status']}")
    print()


def run(filepath: str):
    """Main pipeline: load → analyze → clean → save."""
    df = load_csv(filepath)

    print("Analyzing data...")
    report = analyze(df)
    print_report(report)

    print("Cleaning data...")
    cleaned_df = clean(df)

    save_cleaned(cleaned_df, filepath)
    save_report(report, filepath)

    print("\n[✓] All done!")


# ── Entry point ─────────────────────────────────────────────
if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python csv_cleaner.py <path_to_csv>")
        print("Example: python csv_cleaner.py sales_data.csv")
        sys.exit(1)

    run(sys.argv[1])
